import { CategoryDef, CuisineDef, Merchant } from "./types";

/**
 * DEMO DATA ONLY.
 *
 * This file exists so Feature #001 (foundation + marketplace UI) can be
 * built and reviewed before Feature #003 (merchant onboarding) and a real
 * database exist. Nothing here should be treated as, or quietly promoted
 * into, a production data source — see /docs/feature-001.md.
 */

export const CATEGORIES: CategoryDef[] = [
  { id: "all", label: "All" },
  { id: "home-cook", label: "Home Cooks" },
  { id: "hawker", label: "Hawkers" },
  { id: "bakery", label: "Bakery" },
  { id: "bulk-orders", label: "Bulk Orders" },
  { id: "drinks", label: "Desserts & Drinks" },
];

export const CUISINES: CuisineDef[] = [
  { id: "all", label: "All Cuisines" },
  { id: "chinese", label: "Chinese" },
  { id: "muslim", label: "Muslim" },
  { id: "indian", label: "Indian" },
  { id: "western", label: "Western" },
];

export const MERCHANTS: Merchant[] = [
  {
    id: "auntie-lakshmi-kitchen",
    name: "Auntie Lakshmi's Kitchen",
    category: "home-cook",
    cuisine: "South Indian, home-cooked",
    neighbourhood: "Toa Payoh",
    blurb: "Banana-leaf meals and fish curry made the way her mother taught her — small batches, cooked to order.",
    rating: 4.9,
    ratingCount: 214,
    etaMinutes: 35,
    distanceKm: 1.2,
    priceFrom: 6.5,
    heroImage: "https://picsum.photos/seed/lakshmi-kitchen/640/480",
    avatarImage: "https://picsum.photos/seed/lakshmi-kitchen-avatar/100/100",
    cuisineType: "indian",
    menuHighlights: [
      { name: "Fish Head Curry Set", price: 9.5 },
      { name: "Banana Leaf Rice", price: 6.5 },
    ],
    isNew: true,
  },
  {
    id: "wei-jie-claypot",
    name: "Wei Jie Claypot Rice",
    category: "hawker",
    cuisine: "Chinese, claypot",
    neighbourhood: "Ang Mo Kio",
    blurb: "Third-generation claypot rice stall, charcoal-fired every order — the crispy rice at the bottom is the whole point.",
    rating: 4.7,
    ratingCount: 861,
    etaMinutes: 40,
    distanceKm: 2.4,
    priceFrom: 7,
    heroImage: "https://picsum.photos/seed/weijie-claypot/640/480",
    avatarImage: "https://picsum.photos/seed/weijie-claypot-avatar/100/100",
    cuisineType: "chinese",
    menuHighlights: [
      { name: "Claypot Chicken Rice", price: 7 },
      { name: "Salted Fish Claypot Rice", price: 8.5 },
    ],
  },
  {
    id: "kak-nur-nasi-lemak",
    name: "Kak Nur's Nasi Lemak",
    category: "home-cook",
    cuisine: "Malay, home-cooked",
    neighbourhood: "Bedok",
    blurb: "Sambal made fresh every morning — she'll tell you it's not real nasi lemak if the sambal was made yesterday.",
    rating: 4.8,
    ratingCount: 176,
    etaMinutes: 30,
    distanceKm: 1.8,
    priceFrom: 5,
    heroImage: "https://picsum.photos/seed/kaknur-nasilemak/640/480",
    avatarImage: "https://picsum.photos/seed/kaknur-nasilemak-avatar/100/100",
    cuisineType: "muslim",
    menuHighlights: [
      { name: "Nasi Lemak Ayam Goreng", price: 6.5 },
      { name: "Nasi Lemak Rendang", price: 7.5 },
    ],
  },
  {
    id: "old-tampines-bakes",
    name: "Old Tampines Bakes",
    category: "bakery",
    cuisine: "Bakery, kaya & pastries",
    neighbourhood: "Tampines",
    blurb: "Small home bakery known for kaya bread and pandan chiffon — bakes twice a week, sells out fast.",
    rating: 4.9,
    ratingCount: 132,
    etaMinutes: 50,
    distanceKm: 3.1,
    priceFrom: 4,
    heroImage: "https://picsum.photos/seed/tampines-bakes/640/480",
    avatarImage: "https://picsum.photos/seed/tampines-bakes-avatar/100/100",
    cuisineType: "chinese",
    menuHighlights: [
      { name: "Kaya Butter Bread", price: 4.5 },
      { name: "Pandan Chiffon Slice", price: 3.5 },
    ],
    isNew: true,
  },
  {
    id: "boon-keng-porridge",
    name: "Boon Keng Teochew Porridge",
    category: "hawker",
    cuisine: "Teochew, porridge",
    neighbourhood: "Kallang",
    blurb: "Century-egg porridge and a dozen small dishes, cooked the way the original coffeeshop stall did it.",
    rating: 4.6,
    ratingCount: 503,
    etaMinutes: 38,
    distanceKm: 2.7,
    priceFrom: 5.5,
    heroImage: "https://picsum.photos/seed/boonkeng-porridge/640/480",
    avatarImage: "https://picsum.photos/seed/boonkeng-porridge-avatar/100/100",
    cuisineType: "chinese",
    menuHighlights: [
      { name: "Century Egg Porridge", price: 5.5 },
      { name: "Braised Pork + 2 Dishes", price: 9 },
    ],
  },
  {
    id: "mrs-tan-tiffin",
    name: "Mrs Tan's Tiffin",
    category: "home-cook",
    cuisine: "Peranakan, home-cooked",
    neighbourhood: "Katong",
    blurb: "Ayam buah keluak and babi pongteh cooked to a family recipe — orders close by 3pm for next-day tiffin.",
    rating: 5,
    ratingCount: 89,
    etaMinutes: 45,
    distanceKm: 4.2,
    priceFrom: 8,
    heroImage: "https://picsum.photos/seed/mrstan-tiffin/640/480",
    avatarImage: "https://picsum.photos/seed/mrstan-tiffin-avatar/100/100",
    cuisineType: "chinese",
    menuHighlights: [
      { name: "Ayam Buah Keluak", price: 12 },
      { name: "Babi Pongteh Set", price: 10 },
    ],
  },
  {
    id: "jurong-west-bento",
    name: "Jurong West Bento Co.",
    category: "bulk-orders",
    cuisine: "Fusion, bento boxes",
    neighbourhood: "Jurong West",
    blurb: "A two-person home operation making grab-and-go bento sets — teriyaki, karaage, always with pickled veg.",
    rating: 4.7,
    ratingCount: 241,
    etaMinutes: 33,
    distanceKm: 1.5,
    priceFrom: 7.9,
    heroImage: "https://picsum.photos/seed/jurong-bento/640/480",
    avatarImage: "https://picsum.photos/seed/jurong-bento-avatar/100/100",
    cuisineType: "western",
    menuHighlights: [
      { name: "Chicken Karaage Bento", price: 8.9 },
      { name: "Salmon Teriyaki Bento", price: 10.9 },
    ],
  },
  {
    id: "yishun-briyani-house",
    name: "Yishun Briyani House",
    category: "hawker",
    cuisine: "Indian-Muslim, briyani",
    neighbourhood: "Yishun",
    blurb: "One-pot mutton briyani, made in small batches so the rice never turns mushy from a steam tray.",
    rating: 4.8,
    ratingCount: 397,
    etaMinutes: 42,
    distanceKm: 3.6,
    priceFrom: 6,
    heroImage: "https://picsum.photos/seed/yishun-briyani/640/480",
    avatarImage: "https://picsum.photos/seed/yishun-briyani-avatar/100/100",
    cuisineType: "muslim",
    menuHighlights: [
      { name: "Mutton Briyani", price: 9.5 },
      { name: "Chicken Briyani", price: 6.5 },
    ],
  },
  {
    id: "clementi-cookie-jar",
    name: "Clementi Cookie Jar",
    category: "bakery",
    cuisine: "Bakery, cookies",
    neighbourhood: "Clementi",
    blurb: "Small-batch salted gula melaka cookies, baked in a HDB kitchen and boxed by hand.",
    rating: 4.9,
    ratingCount: 118,
    etaMinutes: 48,
    distanceKm: 2.9,
    priceFrom: 9,
    heroImage: "https://picsum.photos/seed/clementi-cookies/640/480",
    avatarImage: "https://picsum.photos/seed/clementi-cookies-avatar/100/100",
    cuisineType: "chinese",
    menuHighlights: [
      { name: "Gula Melaka Cookie Box (6pc)", price: 9 },
      { name: "Pandan Kaya Cookie Box (6pc)", price: 9 },
    ],
  },
  {
    id: "punggol-poke-house",
    name: "Punggol Poke House",
    category: "bulk-orders",
    cuisine: "Poke bowls, healthy",
    neighbourhood: "Punggol",
    blurb: "Build-your-own poke bowls from a young couple running it out of a tiny kitchen — fresh, no MSG, no shortcuts.",
    rating: 4.6,
    ratingCount: 165,
    etaMinutes: 36,
    distanceKm: 2.1,
    priceFrom: 9.9,
    heroImage: "https://picsum.photos/seed/punggol-poke/640/480",
    avatarImage: "https://picsum.photos/seed/punggol-poke-avatar/100/100",
    cuisineType: "western",
    menuHighlights: [
      { name: "Salmon Poke Bowl", price: 12.9 },
      { name: "Chicken Teriyaki Bowl", price: 10.9 },
    ],
  },
  {
    id: "geylang-teh-tarik",
    name: "Geylang Teh Tarik Corner",
    category: "drinks",
    cuisine: "Drinks, teh tarik & bandung",
    neighbourhood: "Geylang",
    blurb: "Hand-pulled teh tarik and calamansi bandung from a stall that's been mixing drinks the same way for 20 years.",
    rating: 4.8,
    ratingCount: 302,
    etaMinutes: 25,
    distanceKm: 1.6,
    priceFrom: 1.8,
    heroImage: "https://picsum.photos/seed/geylang-tehtarik/640/480",
    avatarImage: "https://picsum.photos/seed/geylang-tehtarik-avatar/100/100",
    cuisineType: "muslim",
    menuHighlights: [
      { name: "Teh Tarik", price: 1.8 },
      { name: "Calamansi Bandung", price: 2.2 },
    ],
    isNew: true,
  },
  {
    id: "toa-payoh-dessert-den",
    name: "Toa Payoh Dessert Den",
    category: "drinks",
    cuisine: "Desserts, chendol & bubble tea",
    neighbourhood: "Toa Payoh",
    blurb: "Small home-based dessert stall — gula melaka chendol and fresh-brewed bubble tea, made to order.",
    rating: 4.9,
    ratingCount: 147,
    etaMinutes: 28,
    distanceKm: 1.4,
    priceFrom: 3.5,
    heroImage: "https://picsum.photos/seed/toapayoh-dessert/640/480",
    avatarImage: "https://picsum.photos/seed/toapayoh-dessert-avatar/100/100",
    cuisineType: "chinese",
    menuHighlights: [
      { name: "Gula Melaka Chendol", price: 3.5 },
      { name: "Brown Sugar Boba", price: 4.5 },
    ],
  },
];
